name: Test project mutual dependency versions

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install graphviz
        run: sudo apt install -y graphviz

      - name: Check for cycles
        run: scripts/check-dependency-cycles.sh 0
      - name: check mismatched dependencies
        run: yarn depcheck
